swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /summarize/audio:
    post:
      operationId: convert.audio
      consumes:
        - multipart/form-data
      produces:
        - "application/json"
      parameters:
        - in: formData
          name: upfile
          type: file
      responses:
        200:
          description: "Successfully summarized"

  /summarize/text:
    post:
      operationId: convert.text
      summary: Creates a new user.
      consumes:
        - application/json
      parameters:
        - in: body
          name : text
          description: The user to create.
          schema:
            type: object
            properties:
              textData:
                type: string
      responses:
        200:
          description: "Successfully summarized"
        201:
          description: Successfully created person in list

  /summarize/context:
    post:
      operationId: convert.context
      summary: Creates a new user.
      consumes:
      - application/json
      parameters:
      - in: body
        name: text
        description: The user to create.
        schema:
          type: object
          properties:
            textData:
              type: string
      responses:
        200:
          description: "Successfully summarized"
        201:
          description: Successfully created person in list